### PR TITLE
Update - January 3rd, 2016

### PR DESCRIPTION
**Pull request by nearbyplayer**
1) Fixed Life_Server
2) Added proper credit
3) Organization to folder structure
4) Added readme
5) Fixed Opium (credit @whocare85)
6) Disabled Global Chat
7) Adjusted Starting Money for all classes

### CODE REVIEW

**Comment by shreddedgaming** [comment]
yo, does this legit work

**Comment by nearbyplayer** [comment]
In theory it does.

**Comment by BarackObamaCare** [comment]
@nearbyplayer  spooki spooki

**Comment by nearbyplayer** [comment]
@BarackObamaCare I'm sorry I don't understand...

**Comment by shreddedgaming** [comment]
how do u install it

**Comment by nearbyplayer** [comment]
@shreddedgaming All you have to do is go and read the readme (on the front page of the repo). That will tell you all you need to know. Since this is such an old version there might be vulnerabilities, etc. So I suggest that you use AltisLife, or check the repositories of @BarackObamaCare he may have a new version.

**Pull request closed without merging**
